use Centro
delete from zona where 1=1;
DBCC CHECKIDENT (zona, RESEED, 1);
DBCC CHECKIDENT (zona, RESEED, 0);
select * from zona;
insert into ZONA values('NORTE');
insert into ZONA values('CENTRO');
insert into ZONA values('SUR');

delete from ESTADO where 1=1;
DBCC CHECKIDENT (estado, RESEED, 1);
DBCC CHECKIDENT (estado, RESEED, 0);
select * from ESTADO;
insert into ESTADO valueS('Aguascalientes', 2);
insert into ESTADO valueS('Colima', 2);
insert into ESTADO valueS('Guanajuato', 2);
insert into ESTADO valueS('Jalisco', 2);
insert into ESTADO valueS('Michoacán', 2);
insert into ESTADO valueS('Nayarit', 2);
insert into ESTADO valueS('Querétaro', 2);
insert into ESTADO valueS('Zacatecas', 2);
insert into ESTADO valueS('Distrito Federal', 2);
insert into ESTADO valueS('Estado de México', 2);
insert into ESTADO valueS('Guerrero', 2);
insert into ESTADO valueS('Hidalgo', 2);
insert into ESTADO valueS('Morelos', 2);
insert into ESTADO valueS('Puebla', 2);
insert into ESTADO valueS('Tlaxcala', 2);


delete from COLONIA where 1=1;
DBCC CHECKIDENT (colonia, RESEED, 1);
DBCC CHECKIDENT (colonia, RESEED, 0);
select * from COLONIA;
insert into COLONIA valueS('CTM EL RISCO', 1);
insert into COLONIA valueS('EL ARBOLILLO 2', 1);
insert into COLONIA valueS('C T M ARAGON', 2);
insert into COLONIA valueS('EDUARDO MOLINA II', 2);
insert into COLONIA valueS('VILLA DE ARAGON', 3);
insert into COLONIA valueS('NUEVA VALLEJO', 3);
insert into COLONIA valueS('SAN JUAN DE ARAGON ', 4);
insert into COLONIA valueS('EL CARMEN', 4);
insert into COLONIA valueS('HEROE DE NACOZARI', 5);
insert into COLONIA valueS('MAXIMINO AVILA CAMACHO', 5);
insert into COLONIA valueS('JOSE MARIA MORELOS Y PAVON', 6);
insert into COLONIA valueS('SAN FELIPE DE JESUS IV', 6);
insert into COLONIA valueS('MARTIN CARRERA I', 7);
insert into COLONIA valueS('MESA LOS HORNOS, TEXCALTENCO', 7);
insert into COLONIA valueS('MIRADOR 1A SECC', 8);
insert into COLONIA valueS('LA PRIMAVERA', 8);
insert into COLONIA valueS('LOMAS ALTAS DE PADIERNA SUR', 9);
insert into COLONIA valueS('LOMAS DE PADIERNA', 9);
insert into COLONIA valueS('SAN PEDRO MARTIR', 10);
insert into COLONIA valueS('TLALCOLIGIA', 10);
insert into COLONIA valueS('SAUZALES CEBADALES', 11);
insert into COLONIA valueS('LA NORIA TEPEPAN', 11);
insert into COLONIA valueS('POTRERO DE SAN BERNARDINO', 12);
insert into COLONIA valueS('SAN ANDRES TOTOLTEPEC', 12);
insert into COLONIA valueS('SAN MIGUEL XICALCO', 13);
insert into COLONIA valueS('SAN JUAN TEPENAHUAC', 13);
insert into COLONIA valueS('LOMAS DE PADIERNA II', 14);
insert into COLONIA valueS('XAXALCO', 14);
insert into COLONIA valueS('ISIDRO FABELA II', 15);
insert into COLONIA valueS('JARDINES DEL SUR', 15);

delete from CALLE where 1=1;
DBCC CHECKIDENT (calle, RESEED, 1);
DBCC CHECKIDENT (calle, RESEED, 0);
select * from CALLE;
insert into CALLE valueS('CABALLERANGO', 1);
insert into CALLE valueS('ABASCAL Y SOUZA', 2);
insert into CALLE valueS('HACIENDA ARENAL', 3);
insert into CALLE valueS('BECERRA Y TANCO', 4);
insert into CALLE valueS('JACARANDA', 5);
insert into CALLE valueS('IGNACIO ALLENDE', 6);
insert into CALLE valueS('BADAJOS', 7);
insert into CALLE valueS('ABUNDIO MARTINEZ', 8);
insert into CALLE valueS('CALDERON DE LA BARCA', 9);
insert into CALLE valueS('JAIME CARRILLO', 10);
insert into CALLE valueS('HACIENDA GUADALUPE', 11);
insert into CALLE valueS('INDEPENDENCIA NORTE', 12);
insert into CALLE valueS('KILIMANJARO', 13);
insert into CALLE valueS('GABAON', 14);
insert into CALLE valueS('BAHIA', 15);
insert into CALLE valueS('CANAL DE AGUAS NEGRAS', 16);
insert into CALLE valueS('GORRION', 17);
insert into CALLE valueS('HACIENDA LA RAJADURA', 18);
insert into CALLE valueS('GENARO GODINA', 19);
insert into CALLE valueS('GAZA', 20);
insert into CALLE valueS('ADOLFO CISNEROS', 21);
insert into CALLE valueS('GRECIA', 22);
insert into CALLE valueS('JOAQUIN ANGULO', 23);
insert into CALLE valueS('BELLOTA', 24);
insert into CALLE valueS('ADRIAN PUGA', 25);
insert into CALLE valueS('JARDINES DE TIVOLI', 26);
insert into CALLE valueS('GONZALO CURIEL', 27);
insert into CALLE valueS('AFRICA', 28);
insert into CALLE valueS('BOLONIA', 29);
insert into CALLE valueS('HILARIA RIOS', 30);



